import type { Rule } from "../types.js";

/**
 * Flags messages whose Message-ID domain differs from the From domain.
 *
 * Attacker pattern: a spoofer sets a recognizable brand in From but the
 * Message-ID is stamped by their own sending infrastructure, so its domain
 * leaks the true origin. Because the Message-ID is generated by the originating
 * system and not normally rewritten in transit, a domain that disagrees with
 * the claimed From domain is a weak consistency hint that the two were produced
 * by different parties.
 *
 * False-positive note: a mismatch is common and entirely legitimate — mailing
 * lists, ESPs, and forwarders routinely stamp Message-IDs from their own
 * domain, and many senders use a separate mail-origin domain. The signal is
 * therefore low severity and exists only as a consistency hint, never a
 * verdict; the caller correlates it with authentication results and its own
 * policy.
 *
 * Noise control for missing/malformed input: the comparison is skipped entirely
 * when either domain is absent (match === null), which covers a missing From,
 * a missing Message-ID, and inputs the parser could not resolve to a real
 * dotted domain (no '@', no domain, or a bare host with no dot). This keeps
 * missing or malformed messages from emitting a signal at all rather than a
 * noisy, low-confidence one.
 */
export const messageIdDomainMismatchRule: Rule = {
  key: "messageId.domainMismatch",
  description: "The Message-ID domain does not match the From domain.",
  evaluate({ metrics }) {
    if (metrics.messageIdDomainMatchesFromDomain !== false) return [];
    // The match is false only when both domains resolved and differ, so the
    // single Message-ID domain is the lone divergent one. Reported as a
    // mismatchedDomains array too, so every consistency signal carries the same
    // divergent-domain field shape regardless of how many domains it compares.
    const mismatchedDomains = metrics.messageIdDomain === null ? [] : [metrics.messageIdDomain];
    return [
      {
        key: "messageId.domainMismatch",
        category: "consistency",
        severity: "low",
        message: "Message-ID domain differs from the From domain.",
        data: {
          fromDomain: metrics.fromDomain,
          messageIdDomain: metrics.messageIdDomain,
          mismatchedDomains,
        },
      },
    ];
  },
};
